### PR TITLE
Support Multiple Video and Option

### PR DESCRIPTION
**Pull request by yuna0x0**
- ConfigureSheet and DefaultsManager added. You may now set the URL directly in the screen saver options. 😁
- Thumbnail added. Feel free to use it, change it, or just discard it.
- You may now use multiple videos in the screen saver options. It will select one video randomly every time.
- Update Swift to version 5

### CODE REVIEW

**Comment by shincurry** [comment]
i wonder which version of xcode did you use, did it worked on Catalina?

i tested it on my mac Catalinta 19A558d, and it just display blank black screen, and screen saver options button is also on disabled.

**Comment by yuna0x0** [comment]
I am using macOS Mojave 10.14.6, Xcode 10.3 (10G8).
The build target may not be ready for Catalina, I will rebuild it later after I update my macOS and Xcode.
Also, I am not sure if the software in Catalina needs to be force codesigned? Or even it needs to be notarized by Apple.

**Comment by shincurry** [comment]
UPDATE: Mojave 10.14.5 (18F132) Xcode 11.0 (11A420a)

blank preference view

屏幕快照 2019-09-24 下午4 48 27

**Comment by yuna0x0** [comment]
**Update: macOS Mojave 10.14.6, Xcode 11.0 (11A420a)**

I have removed some deprecated methods and changing those to new methods, change the macOS deployment target to 10.14, and clean up some redundant code.

~The new build works fine on my side. If the issue persists, I will keep track on it.~

**Comment by yuna0x0** [comment]
I can reproduce the issue by using a new account. Working on to fix it.

**Comment by yuna0x0** [comment]
Done! (>ω<）
The new build should now work fine.

**Comment by shincurry** [comment]
congrats!

**Pull request merged**
